### ISSUE TITLE
Fill GB TAC Representative Seat

### ISSUE THREAD

**Issue by kaywilliams** [ossf/gb-strategy-committee#10]
The OpenSSF charter calls for one GB seat to be filled by a TAC representative.

**Comment by kaywilliams** [comment]
First step - modify OpenSSF charter to handle exception with TAC chair and Related Member companies. Charter modification proposed with GB vote deadline set at 9/11.

**Comment by LindsayLF** [comment]
Charter amendments are approved and adopted.  The updated charter has been added here: https://github.com/ossf/foundation

**Comment by dlorenc** [comment]
Here's the relevant charter change:

> g) If the TAC chairperson cannot vote on the Governing Board by operation of Section 3.f., then the TAC will select another of its representatives (who will not be prohibited from voting on the Governing Board by operation of Section 3.f.) to be the TAC Representative.

So now It's up to the TAC to choose this representative.

**Comment by dlorenc** [comment]
I put this one on the TAC agenda for 9/22

**Comment by kaywilliams** [comment]
Dan Lorenc is the TAC nominee.
