### ISSUE TITLE
Press Release on 10-29-2020

### ISSUE THREAD

**Issue by kaywilliams** [ossf/gb-strategy-committee#11]
Issue Press Release on 10-30-2020 with OpenSSF progress including new members, GB and TAC formation and working groups/working group progress.

**Comment by dlorenc** [comment]
Do we want to track collecting individual WG updates here?

**Comment by kaywilliams** [comment]
I added a separate issue for individual WGs:

https://github.com/ossf/gb-strategy-committee/issues/13

**Comment by kaywilliams** [comment]
We discussed this timeline:
- 9/30(ish) - draft
- 10/15 - deadline for submissions
- 10/30 - release date

Do we know yet who will be handling the PR comms for LF?  We should also tee up comms from member companies to amplify.

**Comment by LindsayLF** [comment]
@kaywilliams In conjunction with working alongside you all on the press release, I'll also be working with our PR firm to get this press release out.  Also, some member companies are already in contact directly with me re: announcing their membership around the same time as our release.

**Comment by kaywilliams** [comment]
On Jennifer's recommendation, moving the press release to 10/29.

**Comment by LindsayLF** [comment]
Draft 1 of the Press Release is delayed to Monday, Oct 5 - will share with Strategy Committee once rec'd.

**Comment by mayakacz** [comment]
Can you please share here as well? Thanks!

**Comment by kaywilliams** [comment]
Hi @mayakacz, this is being shared with the Governing Board rather than the strategy committee since we don't want to undermine the announcement by sharing publicly ahead of time. Note: The strategy committee meetings and discussions are public. Let me know if questions.

**Comment by LindsayLF** [comment]
Press Release went out on 10/29:
https://openssf.org/press-release/2020/10/29/open-source-security-foundation-announces-education-courses-and-participation-initiatives-to-advance-its-commitment-to-securing-the-worlds-software-infrastructure/
