### ISSUE TITLE
Announce new GB members

### ISSUE THREAD

**Issue by kaywilliams** [ossf/gb-strategy-committee#12]
Fill remaining seats on the OpenSSF Governing Board:

- [Member Representatives](https://github.com/ossf/gb-strategy-committee/issues/9)
- [Technical Advisory Council Representative](https://github.com/ossf/gb-strategy-committee/issues/10)
- [Security Community Individual Representative](https://github.com/ossf/tac/issues/22)

**Comment by LindsayLF** [comment]
10/15: Nomination Email Sent to all Member Company Voting Contacts

**Comment by LindsayLF** [comment]
New board members were announced via press release & OpenSSF Website on Oct-29.
