### ISSUE TITLE
Announce 'Fundamentals of Developing Secure Software' edX course

### ISSUE THREAD

**Issue by kaywilliams** [ossf/gb-strategy-committee#14]
Let's announce the 'Fundamentals of Developing Secure Software' as an offering branded by OpenSSF. Steps include the following:

- Identify how we will expose the course on the OpenSSF website (work with Best Practices WG)
- Review plan with the TAC for a technical decision (content and website exposure)
- Review plan with the GB for OpenSSF decision on OpenSSF branding.

**Comment by kaywilliams** [comment]
Adding some timelines:

- Sept 14 - discussion in Best Practices WG
- Week of Sept 14 - vote from Best Practices WG
- Sept 22 - Best Practices WG brings proposal to TAC

Open question:
- Does GB also need to vote on use of OpenSSF brand for edX course?

**Comment by kaywilliams** [comment]
* Working group to decide (Doodle poll, ends Thursday, Sept 17, 11pm Eastern Time https://doodle.com/poll/wkwgpzmbhmmgdy3f)
* TAC to review along with other wg charters

No extra process needed.

**Comment by kaywilliams** [comment]
Created an issue to review the communications plan at an upcoming strategy meeting, ideally 9/28: https://github.com/ossf/gb-strategy-committee/issues/16

**Comment by LindsayLF** [comment]
edX Course announced via the press release & blog on Oct 29:

**Press Release:** https://openssf.org/press-release/2020/10/29/open-source-security-foundation-announces-education-courses-and-participation-initiatives-to-advance-its-commitment-to-securing-the-worlds-software-infrastructure/
**Blog:** https://openssf.org/blog/2020/10/29/announcing-secure-software-development-edx-course-sign-up-today/
