### ISSUE TITLE
Announce new members

### ISSUE THREAD

**Issue by kaywilliams** [ossf/gb-strategy-committee#15]
Announce new OpenSSF members

**Comment by kaywilliams** [comment]
Do we want to specifically recruit additional members ahead of the 10/30 announce? We have a solid group currently. Perhaps we let membership grow organically at this point?

**Comment by mayakacz** [comment]
Have there been requests for additional companies to join already?
I wouldn't feel the pressure to go 'get' new members, but would want to make sure anyone who's already expressed interest has had a chance to participate.

**Comment by kaywilliams** [comment]
The LF has been reaching out to companies, as well as fielding new requests.

**Comment by LindsayLF** [comment]
@kaywilliams this item can be closed.  Updated OpenSSF members list shared with PR Firm for the press release Thanks!

**Comment by kaywilliams** [comment]
Thanks Lindsay.
