### ISSUE TITLE
Review edX course communications plan

### ISSUE THREAD

**Issue by kaywilliams** [ossf/gb-strategy-committee#16]
Communications plan:
- website (openssf.org) - how do we want to expose educational materials generally, and this course specifically, on the OpenSSF website (openssf.org) (Lindsay can help us review and implement with the website designers)
- press release - draft a paragraph for how we want to describe the course in our press release (Lindsay can help us  work with the PR firm to wordsmith and finalize)
- blog - do we want to have a blog article specific to the course?  (Lindsay is working on setting up blog capability for the website, more details later)
- anything else?

**Comment by david-a-wheeler** [comment]
@LindsayLF - can we talk soon (maybe via Slack) to start working out a communications plan? Basically, how will we do a blog post, what changes should be done on the OpenSSF website (and by when)? What needs to be done by when to make that happen? It doesn't need to be complicated, the main issue is that we need to know the deadlines.

**Comment by LindsayLF** [comment]
Hi @kaywilliams and @david-a-wheeler, please see notes below:

- Website: I recommend that we add a "learn" tab to the website where we can house this training & subsequent trainings.  
- Press Release: @david-a-wheeler please send me a concise list of bullet points (or short summary) **by Wed. Sept 30** and we'll share this with the PR firm to include in the release.
-Blog: The blog tab of the website it ready - but will not be visible until we have blog content to share :) If the courses are not 100% ready by the time of the press release (10/29) it may be good to release a blog on the date they become fully available? Thoughts?

**Comment by david-a-wheeler** [comment]
Flavia Cioanca (LF Education) has informed me that for the security course the plan is:

* Oct 28 - Course pages are published & public enrollment is open. A limited number of beta testers can be given early access at this time if desired.
* Oct 29 - Official announcement about course.
* November 5 - course content available.

**Comment by david-a-wheeler** [comment]
@LindsayLF - I don't think Flavia normally uses GitHub, so I'll send you a "concise list of bullet points/summary" by email.

**Comment by kaywilliams** [comment]
@david-a-wheeler, @LindsayLF - regarding the blog. Can we make the blog available on the 29th, and update it on the 5th once course content is available?  I am thinking it would be nice to have the PR link to the blog.

**Comment by kaywilliams** [comment]
@david-a-wheeler, @xcorail, @LindsayLF - for the website, I recommend we use the word 'training' rather than 'learn'. Learn could be confused with 'Learn about the OpenSSF' rather than 'access learning materials'.  The Linux Foundation website uses the term 'training'. Thoughts?  

Would we want the new menu item to be added between 'Governance' and 'FAQ'? What would happen when the item is selected - a drop down menu?, a web page? What would the content of the submenu or web page be?

**Comment by david-a-wheeler** [comment]
@kaywilliams - great point, "training" works for me!

I think the blog should point to the training enrollment page. EdX likes to have a short period where people can "enroll" before the course is available anyway. That will give people something they can do immediately *and* give them access when it's opened.

I separately sent, via email, a summary for the press release, along with some details in case they help.

**Comment by xcorail** [comment]
@kaywilliams 
- 👍🏾 for the `training` instead of `learn`
- However, I am not sure about adding a new menu **now**, as there will be only one entry. I would wait for at least another entry available to create such a menu. In the meantime I would point to the training enrolment page from the blog, and also from the `Resources` section. But if you go for the menu, my preference would go for a drop down with an entry `<title> on EdX`

**Comment by kaywilliams** [comment]
@xcorail, @david-a-wheeler, @LindsayLF  -  I would like to include an item on the menu, even if we only have one course for now. This helps us demonstrates momentum for OpenSSF overall. If we put the course under the blog or resources, it is harder to find. How about a menu item like the following:

Training
> Secure Software Development Fundamentals

For the website UI, I would rather focus on the training content (secure software delivery fundamentals), rather than the deliver method (edX).

Thoughts?

**Comment by xcorail** [comment]
Ok with your proposal @kaywilliams

**Comment by fcioanca** [comment]
You can list either the professional certificate, or the 3 courses within the program. For example, on our training website, we do not promote the professional certificates (we currently have 3 of them). We only promote the individual courses. CNCF and HL do the same

**Comment by LindsayLF** [comment]
@kaywilliams @david-a-wheeler 
Confirming the following cadence for blog posting: 
- 10/29: Post Blog about the courses, with directions on how to sign up 
- 11/5: Update the blog post to reflect that the course is now live

@kaywilliams - Synthesizing from emails & GH Issues:
Website UI for Course(s):
1. Add "Training" to the main header menu (between Governance & FAQ)
2. When "Training" is selected, the user will be brought to a page that houses information on all 3 courses available (Similiar to https://www.hyperledger.org/learn/training)
3. At the top of the Training Page there will be quick nav links for users to "jump" to the course description they want to review. (Course descriptions & links to edX will be similar to hyperledger's set up.)
> In the future, as more courses are made available - we can tweak and update this design.  Did I miss anything?

**Comment by david-a-wheeler** [comment]
I drafted a blog post specifically about the courses here: https://docs.google.com/document/d/18xV_RX-wALdgLTHrwL4-AfjwWoAe5cWylGeTqZvQEEs/edit
I granted a few likely people access; please let me know if you would like access! Please "suggest" when you can (so your changes can be simply accepted), but if that's not reasonable, by all means highlight and add a comment.

**Comment by kaywilliams** [comment]
Looks good.  Closing.
