### ISSUE TITLE
Town Hall meeting week of November 9

### ISSUE THREAD

**Issue by kaywilliams** [ossf/gb-strategy-committee#18]
This issue is to track planning for a two-hour all OpenSSF Townhall meeting the week of November 9.

Draft Agenda
* Welcome and Overview - Kay (10 minutes)
* Governing Board and Strategy Committee - Kay (10 minutes)
* Technical Advisory Committee overview and updates - Ryan (10 minutes)
* Working Groups - each group 10 minutes (60 minutes total)
* Discussion + Q & A (30 minutes)

**Comment by kaywilliams** [comment]
Next step - @kaywilliams working on an email to share background for the meeting to TAC, GB and WG Leads, and ask for their availability the week of November 9 via Doodle poll.

**Comment by LindsayLF** [comment]
Date & Time Confirmed for Town Hall:
When: MONDAY Nov 9, 2020 10:00 AM - 12:00 PM Pacific Time (US and Canada) 

Register in advance for this meeting:
https://zoom.us/meeting/register/tJEoc-CqpjkvHdworhPXD8GUS_U9ox0TYWJr
After registering, you will receive a confirmation email containing information about joining the meeting.

**Comment by kaywilliams** [comment]
Done.
