### ISSUE TITLE
Elevate 'Values' and 'Code of Conduct' on website and create mechanism for reporting concerns

### ISSUE THREAD

**Issue by kaywilliams** [ossf/gb-strategy-committee#24]
Our OpenSSF values are currently described in the FAQ section of our website. Consider moving these to a separate page, and making that page accessible from a top level menu (perhaps ‘About’ or ‘Community’). Consider exposing the LF Code of Conduct as well?

Also, we don’t provide a mechanism for individuals to raise concerns if they experience behavior that runs contrary to OpenSSF values or the LF Code of Conduct.  Consider creating a form where people can raise concerns (anonymously if desired). In doing this, we should consider what process we will follow in responding to concerns.

**Comment by dlorenc** [comment]
At least for repos/projects I think we need a code-of-conduct@openssf.org mailing list. For now this can probably just fwd to either the governing board or LF staff. 

@LindsayLF - do you know how these are setup in other LF foundations?

**Comment by LindsayLF** [comment]
@dlorenc @kaywilliams Yes, I can create an email account for code of conduct reporting.  When would like this live by? Thanks!

**Comment by LindsayLF** [comment]
Hi @dlorenc @kaywilliams - the alias conduct@openssf.org has been created, thanks!

**Comment by kimsterv** [comment]
The working doc for code of conduct lives here - https://docs.google.com/document/d/1le5ernYmaYEymOXey25tZ64B4cFYMVI3BS8Pa59LWvg/edit?ts=5fb54257#heading=h.q6wov7bqvkj9

@dlorenc left a comment at the bottom wondering why we can't reuse https://www.contributor-covenant.org/ for this.

**Comment by kaywilliams** [comment]
Code of Conduct approved by the GB and posted on the website under the 'About' tab.
