### ISSUE TITLE
Email list is restricted, should it be public?

### ISSUE THREAD

**Issue by joshuagl** [ossf/gb-strategy-committee#5]
I tried to join the openssf-gb-strategy-committee@ list by clicking the "Apply For Membership In This Group" button, was redirected to LF SSO (rather than using my existing and logged in lists.openssf.org credentials) and, upon registering and trying to subscribe, received the error message:
> Only public groups are supported, Group: lf-JOSSI/openssf-gb-strategy-committee is not a public group

Should this list be public and open for all to join?

**Comment by kaywilliams** [comment]
Yes, the email list should be public. @lmays@linuxfoundation.org can you help us?

**Comment by LindsayLF** [comment]
@joshuagl @kaywilliams I am looking into this and should know more soon, thanks for your patience.

**Comment by LindsayLF** [comment]
@joshuagl - Everything should be all fixed, can you try again? Thanks for your patience!

**Comment by joshuagl** [comment]
Thanks @LindsayLF, I have been able to join. 

I was still redirected through the LF SSO, which didn't happen when I joined other lists earlier on. Was that an intentional change? Is the LF SSO now used for other OpenSSF lists?

**Comment by LindsayLF** [comment]
Hi @joshuagl - thank you for your patience! We are rolling SSO across different projects. Some projects will have SSO enabled already, some won’t. In the end, all projects mailing lists using groups.io will have SSO enabled. I hope that helps clarify!

**Comment by joshuagl** [comment]
Makes sense, thanks for taking the time to respond to my questions @LindsayLF
