### ISSUE TITLE
'Get Involved' User Experience

### ISSUE THREAD

**Issue by kaywilliams** [ossf/gb-strategy-committee#7]
Replace the current 'Join' button with a 'Get Involved' button that makes it easy for individuals and organizations to participate.

**Comment by kaywilliams** [comment]
Draft proposal [here](https://docs.google.com/document/d/12rDsqWyMZU8F62EEX3V__RISONYU0k0BlWKT23x5p2E/edit#heading=h.4imn6p408qrx). Comments welcome.

**Comment by mayakacz** [comment]
I like this proposal.
Would also suggest updating the text on READMEs for TAC (? and each WG?) with some of this info.

**Comment by kaywilliams** [comment]
Website updated - https://openssf.org/getinvolved/
