### ISSUE TITLE
Fill GB Member Representative Seats

### ISSUE THREAD

**Issue by kaywilliams** [ossf/gb-strategy-committee#9]
Fill three remaining GB member representative seats

**Comment by joshuagl** [comment]
What's the process for this? Should folks self nominate?

**Comment by kaywilliams** [comment]
We will have more details later, but the high level timeline and process is below.  More information about the Governing Board and representatives generally can found in the [Open Source Security Foundation Charter](https://docs.google.com/document/d/1WVyKpP88IWSL_PeyNNei5a_l7O0_G_Gy7tTLB7zOEdo/edit?usp=sharing).

- Tuesday, October 13 deadline for completed Participation Agreements
- Thursday, October 15: nomination process begins
- Tuesday, October 20 at 5pm PT: nomination period ends
- Wednesday, October 21: voting period begins
- Wednesday, October 28 at 5pm PT: voting period ends
- Announce new GB members on Friday, October 29

**Comment by reagir007** [comment]
@kaywilliams any details on the self-nomination process? Thanks ... anand

**Comment by kaywilliams** [comment]
Thanks for your question. In the past we've used a Google Form to capture self nominations and some sort of polling service for voting. @LindsayLF will share more details as we get closer.

**Comment by kaywilliams** [comment]
Also, I can share that the request for nomination will go to the individual identified as the 'Primary Project Contact' on Exhibit A of the [Participation Agreement](https://github.com/ossf/foundation/blob/main/Review%20Copy%20Only%20-%20Not%20for%20Execution_OpenSSF%20Participation%20Agreement%20and%20Charter%20(rev.%202020%2009%2011).pdf). This person will also be responsible for casting the vote.

**Comment by LindsayLF** [comment]
New Board Members are confirmed as of 10/29:
Jeffrey Eric Altman, AuriStor, Inc.
Lech Sandecki, Canonical
Anand Pashupathy, Intel Corporation
